version: '2'
services :
  kimsufi :
    build : .
    environment:
      SERVER_WARN: 143sys1
      ZONE: rbx
      TOKEN: 209386414:AAFCurz_WsnOYmXzaITU6EVxAq7Z9fyKHQI
      USERID: 143428947
      TIMESLEEP: 2
      TIMERENOTIFY: 60
    hostname: kimsufi
