version: '2'
services :
  kimsufi :
    build : .
    environment:
      SERVER_WARN: 143sys1
      ZONE: rbx
      TOKEN:
      USERID: 
      TIMESLEEP: 1
      TIMERENOTIFY: 60
    hostname: kimsufi
